import {
  createAgentSession,
  ModelRuntime,
  SessionManager,
} from "@earendil-works/pi-coding-agent";
import { execSync } from "node:child_process";
import { config } from "../config.js";
import { trello } from "../trello/client.js";
import { github } from "../github/client.js";
import {
  startedEmbed,
  progressEmbed,
  prReadyEmbed,
  failedEmbed,
} from "../discord/embeds.js";
import type { DiscordBot } from "../discord/bot.js";
import { store } from "../state/store.js";
import { createWorktree, removeWorktree } from "./worktree.js";

let modelRuntime: ModelRuntime | undefined;

/** Run one card end-to-end: worktree → pi agent → push → PR → CI. */
export async function runCard(cardId: string, bot: DiscordBot): Promise<void> {
  const job = store.get(cardId);
  if (!job) return;
  const card = await trello.getCard(cardId);
  const { dir, branch } = createWorktree(cardId);
  store.setRunning(cardId, branch);
  await bot.send(startedEmbed(card.name, branch));

  try {
    if (!modelRuntime) modelRuntime = await ModelRuntime.create();

    const prompt = [
      `You are a factory coding agent. Complete this task from our Trello board.`,
      ``,
      `Task: ${card.name}`,
      card.desc ? `Details:\n${card.desc}` : ``,
      ``,
      `Rules:`,
      `- Work only in the current directory.`,
      `- Make the smallest correct change that fulfills the task.`,
      `- Run the project's tests if they exist; fix failures you cause.`,
      `- When done, commit all changes with a message starting "factory: ".`,
    ].join("\n");

    const { session } = await createAgentSession({
      cwd: dir,
      modelRuntime,
      sessionManager: SessionManager.inMemory(dir),
    });

    session.subscribe((event) => {
      if (event.type === "tool_execution_start") {
        void bot.send(progressEmbed(card.name, `tool: ${event.toolName}`));
      }
    });

    await session.prompt(prompt);
    session.dispose();

    // Push branch and open PR
    execSync(`git -C ${dir} push -u origin ${branch}`, { stdio: "inherit" });
    const prUrl = await github.createPR(
      branch,
      `factory: ${card.name}`,
      `Auto-generated by the factory from [Trello card ${cardId}](${card.url})`
    );
    await bot.send(progressEmbed(card.name, `PR opened — waiting for CI: ${prUrl}`));

    // CI gate: only move to Review when CI passes
    const ci = await github.waitForCI(branch, {
      timeoutMs: config.factory.ciTimeoutMs,
    });
    if (ci !== "passed") {
      const msg = ci === "timeout" ? "CI timed out" : "CI failed";
      store.setFailed(cardId, msg);
      await bot.send(failedEmbed(card.name, `${msg} — ${prUrl}`));
      await trello
        .addComment(cardId, `Factory: ${msg}. PR: ${prUrl}`)
        .catch(() => {});
      return; // card stays in Ready for manual re-trigger
    }

    store.setReview(cardId, prUrl);
    await bot.send(prReadyEmbed(card.name, prUrl));
    await trello.moveCard(cardId, config.trello.reviewListId());
    await trello.addComment(cardId, `Factory opened PR: ${prUrl}`);
  } catch (err) {
    const msg = err instanceof Error ? err.message : String(err);
    store.setFailed(cardId, msg);
    await bot.send(failedEmbed(card.name, msg));
    await trello.addComment(cardId, `Factory run failed: ${msg}`).catch(() => {});
  } finally {
    removeWorktree(cardId);
  }
}
